services:
  dashboard-app:
    image: dashboard-ft:latest
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        - NODE_ENV=production
        - PORT=3000
        - PUBLIC_SUPABASE_URL=${SUPABASE_URL}
        - PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${SUPABASE_PUBLISHABLE_DEFAULT_KEY}
    ports:
      - "3001:3000"
    container_name: dashboard-${ENVIRONMENT:-production}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_PUBLISHABLE_DEFAULT_KEY=${SUPABASE_PUBLISHABLE_DEFAULT_KEY}
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true